export const auth = {
  LOGIN_SUCCESS: "LOGIN_SUCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
};

export const messages = {
  SET_ERR_MESSAGE: "SET_ERR_MESSAGE",
  CLEAR_ERR_MESSAGE: "CLEAR_ERR_MESSAGE",
  SET_MESSAGE: "SET_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
};

// export const operations = {
//   GET_MDA_START: "GET_MDA_START",
//   GET_MDA_SUCCESS: "GET_MDA_SUCCESS",
//   GET_MDA_FAIL: "GET_MDA_FAIL",

//   GET_MDAS_START: "GET_MDAS_START",
//   GET_MDAS_SUCCESS: "GET_MDA_SUCCESS",
//   GET_MDAS_FAIL: "GET_MDAS_FAIL",

//   CREATE_MDA_START: "CREATE_MDA_START",
//   CREATE_MDA_SUCCESS: "CREATE_MDA_SUCCESS",
//   CREATE_MDA_FAIL: "CREATE_MDA_FAIL",

//   UPDATE_MDA_START: "UPDATE_MDA_START",
//   UPDATE_MDA_SUCCESS: "UPDATE_MDA_SUCCESS",
//   UPDATE_MDA_FAIL: "UPDATE_MDA_FAIL",

//   DELETE_MDA_START: "DELETE_MDA_START",
//   DELETE_MDA_SUCCESS: "DELETE_MDA_SUCCESS",
//   DELETE_MDA_FAIL: "DELETE_MDA_FAIL",

//   GET_DEPT_START: "GET_DEPT_START",
//   GET_DEPT_SUCCESS: "GET_DEPT_SUCCESS",
//   GET_DEPT_FAIL: "GET_DEPT_FAIL",

//   GET_DEPTS_START: "GET_DEPTS_START",
//   GET_DEPTS_SUCCESS: "GET_DEPTS_SUCCESS",
//   GET_DEPTS_FAIL: "GET_DEPTS_FAIL",

//   CREATE_DEPT_START: "CREATE_DEPT_START",
//   CREATE_DEPT_SUCCESS: "CREATE_DEPT_SUCCESS",
//   CREATE_DEPT_FAIL: "CREATE_DEPT_FAIL",

//   UPDATE_DEPT_START: "UPDADTE_DEPT_START",
//   UPDATE_DEPT_SUCCESS: "UPDATE_DEPT_SUCCESS",
//   UPDATE_DEPT_FAIL: "UPDATE_DEPT_FAIL",

//   DELETE_DEPT_START: "DELETE_DEPT_START",
//   DELETE_DEPT_SUCCESS: "DELETE_DEPT_SUCCESS",
//   DELETE_DEPT_FAIL: "DELETE_DEPT_FAIL",

//   GET_GENERAL_FILE_START: "GET_GENERAL_FILE_START",
//   GET_GENERAL_FILE_SUCCESS: "GET_GENERAL_FILE_SUCCESS",
//   GET_GENERAL_FILE_FAIL: "GET_GENERAL_FILE_FAIL",

//   GET_GENERAL_FILES_START: "GET_GENERAL_FILES_START",
//   GET_GENERAL_FILES_SUCCESS: "GET_GENERAL_FILES_SUCCESS",
//   GET_GENERAL_FILES_FAIL: "GET_GENERAL_FILES_FAIL",

//   CREATE_GENERAL_FILE_START: "CREATE_GENERAL_FILE_START",
//   CREATE_GENERAL_FILE_SUCCESS: "CREATE_GENERAL_FILE_SUCCESS",
//   CREATE_GENERAL_FILE_FAIL: "CREATE_GENERAL_FILE_FAIL",

//   UPDATE_GENERAL_FILE_START: "UPDATE_GENERAL_FILE_START",
//   UPDATE_GENERAL_FILE_SUCCESS: "UPDATE_GENERAL_FILE_SUCCESS",
//   UPDATE_GENERAL_FILE_FAIL: "UPDATE_GENERAL_FILE_FAIL",

//   DELETE_GENERAL_FILE_START: "DELETE_GENERAL_FILE_START",
//   DELETE_GENERAL_FILE_SUCCESS: "DELETE_GENERAL_FILE_SUCCESS",
//   DELETE_GENERAL_FILE_FAIL: "DELETE_GENERAL_FILE_FAIL",

//   ADD_DOCUMENT_TO_FILE_START: "ADD_DOCUMENT_TO_FILE_START",
//   ADD_DOCUMENT_TO_FILE_SUCCESS: "ADD_DOCUMENT_TO_FILE_SUCCESS",
//   ADD_DOCUMENT_TO_FILE_FAIL: "ADD_DOCUMENT_TO_FILE_FAIL",

//   REMOVE_DOCUMENT_FROM_FILE_START: "REMOVE_DOCUMENT_FROM_FILE_START",
//   REMOVE_DOCUMENT_FROM_FILE_SUCCESS: "REMOVE_DOCUMENT_FROM_FILE_SUCCESS",
//   REMOVE_DOCUMENT_FROM_FILE_FAIL: "REMOVE_DOCUMENT_FROM_FILE_FAIL",

//   MOVE_FILE_START: "MOVE_FILE_START",
//   MOVE_FILE_SUCCESS: "MOVE_FILE_SUCCESS",
//   MOVE_FILE_FAIL: "MOVE_FILE_FAIL",

//   GET_INCOMING_MAIL_START: "GET_INCOMING_MAIL_START",
//   GET_INCOMING_MAIL_SUCCESS: "GET_INCOMING_MAIL_SUCCESS",
//   GET_INCOMING_MAIL_FAIL: "GET_INCOMING_MAIL_FAIL",

//   GET_INCOMING_MAILS_START: "GET_INCOMING_MAILS_START",
//   GET_INCOMING_MAILS_SUCCESS: "GET_INCOMING_MAILS_SUCCESS",
//   GET_INCOMING_MAILS_FAIL: "GET_INCOMING_MAILS_FAIL",

//   CREATE_INCOMING_MAIL_START: "CREATE_INCOMING_MAIL_START",
//   CREATE_INCOMING_MAIL_SUCCESS: "CREATE_INCOMING_MAIL_SUCCESS",
//   CREATE_INCOMING_MAIL_FAIL: "CREATE_INCOMING_MAIL_FAIL",

//   UPDATE_INCOMING_MAIL_START: "UPDATE_INCOMING_MAIL_START",
//   UPDATE_INCOMING_MAIL_SUCCESS: "UPDATE_INCOMING_MAIL_SUCCESS",
//   UPDATE_INCOMING_MAIL_FAIL: "UPDATE_INCOMING_MAIL_FAIL",

//   DELETE_INCOMING_MAIL_START: "DELETE_INCOMING_MAIL_START",
//   DELETE_INCOMING_MAIL_SUCCESS: "DELETE_INCOMING_MAIL_SUCCESS",
//   DELETE_INCOMING_MAIL_FAIL: "DELETE_INCOMING_MAIL_FAIL",

//   GET_OUTGOING_MAIL_START: "GET_OUTGOING_MAIL_START",
//   GET_OUTGOING_MAIL_SUCCESS: "GET_OUTGOING_MAIL_SUCCESS",
//   GET_OUTGOING_MAIL_FAIL: "GET_OUTGOING_MAIL_FAIL",

//   GET_OUTGOING_MAILS_START: "GET_OUTGOING_MAILS_START",
//   GET_OUTGOING_MAILS_SUCCESS: "GET_OUTGOING_MAILS_SUCCESS",
//   GGET_OUTGOING_MAILS_FAIL: "GET_OUTGOING_MAILS_FAIL",

//   CREATE_OUTGOING_MAIL_START: "CREATE_OUTGOING_MAIL_START",
//   CREATE_OUTGOING_MAIL_SUCCESS: "CREATE_OUTGOING_MAIL_SUCCESS",
//   CREATE_OUTGOING_MAIL_FAIL: "CREATE_OUTGOING_MAIL_FAIL",

//   GET_USER_START: "GET_USER_START",
//   GET_USER_SUCCESS: "GET_USER_SUCCESS",
//   GET_USER_FAIL: "GET_USER_FAIL",

//   GET_USERS_START: "GET_USERS_START",
//   GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
//   GET_USERS_FAIL: "GET_USERS_FAIL",

//   CREATE_USER_START: "CREATE_USER_START",
//   CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
//   CREATE_USER_FAIL: "CREATE_USER_FAIL",

//   UPDATE_USER_START: "UPDATE_USER_START",
//   UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
//   UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

//   DELETE_USER_START: "DELETE_USER_START",
//   DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
//   DELETE_USER_FAIL: "DELETE_USER_FAIL",
// };

export const operations = {
  GET_MDA: "GET_MDA",
  GET_MDA_FAIL: "GET_MDA_FAIL",
  GET_ALLMDAS: "GET_ALLMDAS",
  GET_ALLMDAS_FAIL: "GET_ALLMDAS_FAIL",
  GET_DEPT: "GET_DEPT",
  GET_DEPT_FAIL: "GET_DEPT_FAIL",
  GET_ALLDEPTS: "GET_ALLDEPTS",
  GET_ALLDEPTS_FAIL: "GET_ALLDEPTS_FAIL",

  GET_ALLFILES: "GET_ALLFILES",

  GET_GENERALFILES: "GET_GENERALFILES",
  GET_ALLFILES_FAIL: "GET_ALLFILES_FAIL",

  GET_GENERALFILES_FAIL: "GET_GENERALFILES_FAIL",
  GET_FILE: "GET_FILE",
  GET_FILE_FAIL: "GET_FILE_FAIL",

  GET_MAILS_SUCCESS: "GET_MAILS_SUCCESS",
  GET_MAILS_FAIL: "GET_MAILS_FAIL",
  GET_MAIL: "GET_MAIL",
  GET_MAIL_FAIL: "GET_MAIL_FAIL",

  GET_INCOMING_MAILS_SUCCESS: "GET_INCOMING_MAILS_SUCCESS",
  GET_INCOMING_MAILS_FAIL: "GET_INCOMING_MAILS_FAIL",
  GET_INCOMING_MAIL_SUCCESS: "GET_INCOMING_MAIL_SUCCESS",
  GET_INCOMING_MAIL_FAIL: "GET_INCOMING_MAIL_FAIL",

  GET_OUTGOING_MAILS_SUCCESS: "GET_OUTGOING_MAILS_SUCCESS",
  GET_OUTGOING_MAILS_FAIL: "GET_OUTGOING_MAILS_FAIL",
  GET_OUTGOING_MAIL_SUCCESS: "GET_OUTGOING_MAIL_SUCCESS",
  GET_OUTGOING_MAIL_FAIL: "GET_OUTGOING_MAIL_FAIL",

  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_USER_PROFILE_FAIL: "GET_USER_PRPFILE_FAIL",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_FAIL: "GET_USER_BY_ID_FAIL",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",
};
