export const auth = {
  LOGIN_SUCCESS: "LOGIN_SUCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
};

export const messages = {
  SET_ERR_MESSAGE: "SET_ERR_MESSAGE",
  CLEAR_ERR_MESSAGE: "CLEAR_ERR_MESSAGE",
  SET_MESSAGE: "SET_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
};

export const operations = {
  GET_MDA: "GET_MDA",
  GET_MDA_FAIL: "GET_MDA_FAIL",
  GET_ALLMDAS: "GET_ALLMDAS",
  GET_ALLMDAS_FAIL: "GET_ALLMDAS_FAIL",
  GET_DEPT: "GET_DEPT",
  GET_DEPT_FAIL: "GET_DEPT_FAIL",
  GET_ALLDEPTS: "GET_ALLDEPTS",
  GET_ALLDEPTS_FAIL: "GET_ALLDEPTS_FAIL",

  GET_ALLFILES: "GET_ALLFILES",
  GET_PERSONALFILES: "GET_PERSONALFILES",
  GET_GENERALFILES: "GET_GENERALFILES",
  GET_ALLFILES_FAIL: "GET_ALLFILES_FAIL",
  GET_PERSONALFILES_FAIL: "GET_PERSONALFILES_FAIL",
  GET_GENERALFILES_FAIL: "GET_GENERALFILES_FAIL",
  GET_FILE: "GET_FILE",
  GET_FILE_FAIL: "GET_FILE_FAIL",

  GET_MAILS_SUCCESS: "GET_MAILS_SUCCESS",
  GET_MAILS_FAIL: "GET_MAILS_FAIL",
  GET_MAIL: "GET_MAIL",
  GET_MAIL_FAIL: "GET_MAIL_FAIL",

  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_USER_PROFILE_FAIL: "GET_USER_PRPFILE_FAIL",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_FAIL: "GET_USER_BY_ID_FAIL",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",
};
